from PyQt5.QtCore import (QCoreApplication, QMetaObject, QRect)
from PyQt5.QtWidgets import *

class Ui_Form(object):
    def setupUi(self, Form):
        if Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(321, 262)
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 321, 261))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.cb_dd = QCheckBox(self.tab)
        self.cb_dd.setObjectName(u"cb_dd")
        self.cb_dd.setGeometry(QRect(124, 10, 31, 16))
        self.cb_second = QCheckBox(self.tab)
        self.cb_second.setObjectName(u"cb_second")
        self.cb_second.setGeometry(QRect(180, 10, 31, 16))
        self.cb_cbss = QCheckBox(self.tab)
        self.cb_cbss.setObjectName(u"cb_cbss")
        self.cb_cbss.setGeometry(QRect(64, 10, 51, 16))
        self.btn_watch = QPushButton(self.tab)
        self.btn_watch.setObjectName(u"btn_watch")
        self.btn_watch.setGeometry(QRect(80, 30, 51, 23))
        self.cb_old = QCheckBox(self.tab)
        self.cb_old.setObjectName(u"cb_old")
        self.cb_old.setGeometry(QRect(10, 10, 41, 16))
        self.btn_open = QPushButton(self.tab)
        self.btn_open.setObjectName(u"btn_open")
        self.btn_open.setGeometry(QRect(160, 30, 41, 23))
        self.btn_close = QPushButton(self.tab)
        self.btn_close.setObjectName(u"btn_close")
        self.btn_close.setGeometry(QRect(160, 60, 41, 23))
        self.pushbtn_login = QPushButton(self.tab)
        self.pushbtn_login.setObjectName(u"pushbtn_login")
        self.pushbtn_login.setGeometry(QRect(4, 60, 51, 23))
        self.pushbtn_login_dd = QPushButton(self.tab)
        self.pushbtn_login_dd.setObjectName(u"pushbtn_login_dd")
        self.pushbtn_login_dd.setGeometry(QRect(4, 30, 51, 23))
        self.te_output = QTextEdit(self.tab)
        self.te_output.setObjectName(u"te_output")
        self.te_output.setGeometry(QRect(0, 90, 311, 141))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushbtn_search = QPushButton(self.tab_2)
        self.pushbtn_search.setObjectName(u"pushbtn_search")
        self.pushbtn_search.setGeometry(QRect(190, 60, 51, 23))
        self.le_pspid = QLineEdit(self.tab_2)
        self.le_pspid.setObjectName(u"le_pspid")
        self.le_pspid.setGeometry(QRect(160, 0, 151, 20))
        self.le_name = QLineEdit(self.tab_2)
        self.le_name.setObjectName(u"le_name")
        self.le_name.setGeometry(QRect(0, 0, 71, 20))
        self.le_telnum = QLineEdit(self.tab_2)
        self.le_telnum.setObjectName(u"le_telnum")
        self.le_telnum.setGeometry(QRect(80, 0, 71, 20))
        self.le_orderid = QLineEdit(self.tab_2)
        self.le_orderid.setObjectName(u"le_orderid")
        self.le_orderid.setGeometry(QRect(0, 60, 181, 20))
        self.textEdit = QTextEdit(self.tab_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(0, 90, 311, 141))
        self.le_address = QLineEdit(self.tab_2)
        self.le_address.setObjectName(u"le_address")
        self.le_address.setGeometry(QRect(0, 30, 311, 20))
        self.pushbtn_go = QPushButton(self.tab_2)
        self.pushbtn_go.setObjectName(u"pushbtn_go")
        self.pushbtn_go.setGeometry(QRect(250, 60, 61, 23))
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"RUSHGO", None))
        self.cb_dd.setText(QCoreApplication.translate("Form", u"dd", None))
        self.cb_second.setText(QCoreApplication.translate("Form", u"2", None))
        self.cb_cbss.setText(QCoreApplication.translate("Form", u"cbss", None))
        self.btn_watch.setText(QCoreApplication.translate("Form", u"&Watch", None))
        self.cb_old.setText(QCoreApplication.translate("Form", u"old", None))
        self.btn_open.setText(QCoreApplication.translate("Form", u"&Open", None))
        self.btn_close.setText(QCoreApplication.translate("Form", u"&Close", None))
        self.pushbtn_login.setText(QCoreApplication.translate("Form", u"LoginN", None))
        self.pushbtn_login_dd.setText(QCoreApplication.translate("Form", u"LoginO", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"Tab 1", None))
        self.pushbtn_search.setText(QCoreApplication.translate("Form", u"Search", None))
        self.le_pspid.setPlaceholderText(QCoreApplication.translate("Form", u"\u8eab\u4efd\u8bc1\u53f7", None))
#if QT_CONFIG(tooltip)
        self.le_name.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_name.setInputMask("")
        self.le_name.setText("")
        self.le_name.setPlaceholderText(QCoreApplication.translate("Form", u"\u59d3\u540d", None))
        self.le_telnum.setText("")
        self.le_telnum.setPlaceholderText(QCoreApplication.translate("Form", u"\u8054\u7cfb\u7535\u8bdd", None))
        self.le_orderid.setPlaceholderText(QCoreApplication.translate("Form", u"\u8ba2\u5355\u7f16\u53f7", None))
        self.le_address.setPlaceholderText(QCoreApplication.translate("Form", u"\u5b89\u88c5\u5730\u5740", None))
        self.pushbtn_go.setText(QCoreApplication.translate("Form", u"Go", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"Tab 2", None))
    # retranslateUi


